// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzeyhboppdnrkwyuhbbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZXloYm9wcGRucmt3eXVoYmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjk2MzgsImV4cCI6MjA1Mjk0NTYzOH0.48-TsrhHwCliw_32lRgMgnsLBjaI2qXc_6nivPPzf_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);